drupal_api.settings:
  type: config_object
  label: 'Settings for pulling from the Drupal API'
  mapping:
    automatic_enabled:
      label: 'Enable Automatic Import of New Data'
      type: boolean
    automatic_frequency:
      label: 'Automatic Import Frequency'
      type: integer
